### ISSUE TITLE
Bug on Xiaomi (MIUI 11.0) - Set Lock Screen

### ISSUE THREAD

**Issue by LudoWeb** [AndreVarandas/cordova-plugin-wallpaper#1]
Hello,

I have two devices : 

- Huawei P20
- Xiaomi Pocophone

This plugin works great on Huawei P20 but not on my Xiaomi (API Level 29 - MIUI 11.0).

I have a problem with this following line (set the lock screen wallpaper) : 
`wallpaperManager.setBitmap(bmp, null, true, WallpaperManager.FLAG_LOCK);`
I don't have any error, but the wallpaper doesn't update.

However, set the wallpaper works fine : 
`wallpaperManager.setBitmap(bmp);`

Do you have any idea about this ?
Thanks,

**Comment by AndreVarandas** [comment]
Hi @LudoWeb thanks for reaching out.

This might be related to a bug in the MIUI. To clarify this, can you also set a lock screen wallpaper from other apps?

**Comment by LudoWeb** [comment]
Thanks for your reply.

Yes, seems to be that. I can't update my wallpaper with Google Wallpaper for example.

However, it's possible to update with :
- "Theme" application
-  Set manually lock screen wallpaper in gallery

**Comment by AndreVarandas** [comment]
Thanks for your feedback,

Im closing this issue as there is no solution (other than the specified above) or work around for it right now - hopefully MIUI will fix this in the upcoming versions.

Please feel free to reopen this issue, if something new comes!
