### ISSUE TITLE
image link

### ISSUE THREAD

**Issue by albasha942021** [AndreVarandas/cordova-plugin-wallpaper#2]
hello
in the plugin the image must be full link like (http://site.com/images/img.png) is that any way to be like that (images/img.png).

**Comment by AndreVarandas** [comment]
Hi @albasha942021 unfortunately it does not support local images. Currently I don't have the time to work on it but feel free to submit a pull request!

**Comment by albasha942021** [comment]
Hello, what do I need to know to be able to program plugins for the Cordova platform?
Are there courses you can recommend to me?

**Comment by AndreVarandas** [comment]
Unfortunately not that I am aware... But there's some documentation here https://cordova.apache.org/docs/en/latest/guide/hybrid/plugins/ and I think ionicframework has also some tutorials on it 🙂

**Comment by albasha942021** [comment]
thank you so much
